### PR TITLE
Fix handling for 5 and 6 plans

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**

### CODE REVIEW

**Comment by will** [comment]
Tim did a thing to fix the 6, but I don't know if it's been merged. I don't
think he's deployed it at least

**Comment by uhoh-itsmaciek** [comment]
#7? It does seem to have the same fix for 6 as here but it does not fix 5. And it does not seem to be merged or deployed.

**Comment by will** [comment]
I gave that one a looks good and I'll give this one a looks good too so
good luck whoever wins

**Comment by uhoh-itsmaciek** [comment]
Sorry @cyberdelia I won.

**Comment by cyberdelia** [comment]
shrug

**Comment by will** [comment]
img

**Pull request merged**
